### ISSUE TITLE
logo contribution

### ISSUE THREAD

**Issue by reallinfo** [deppiedave64/elternbrief#1]
Hi @deppiedave64 I design logos for projects that do not have logo for supporting open source projects. I think this project doesn't have a logo. That's why I designed a logo. If you like it, please tell me if you have any other suggestions. I will wait for feedback. Have a nice day!

![elt](https://user-images.githubusercontent.com/36298335/57015825-8a349a80-6c1f-11e9-8e49-60d4cee1e6ec.jpg)

![elt2](https://user-images.githubusercontent.com/36298335/57015834-8f91e500-6c1f-11e9-9545-83219607f337.png)

**Comment by deppiedave64** [comment]
@reallinfo thank You so much for Your kind help! The logos look really awesome, I especially like the blue version. Next week I will talk to my teachers and show them Your suggestion. Maybe they would like a certain color scheme that would go well with our school website's design. But other than that, I think they will like them as well!

**Comment by reallinfo** [comment]
Oh okay. I will wait for feedback. I am glad you like it :)

**Comment by deppiedave64** [comment]
Just talked to my teacher. He likes it as well! Apparently our school does not have a uniform color scheme for their design yet, so for now we would go for the blue version. I would be very happy to use it for the project!

**Comment by reallinfo** [comment]
I sent a pr. (also with svg versions) So you can change colors at any time. https://github.com/deppiedave64/elternbrief/pull/2

**Comment by deppiedave64** [comment]
Merged it just now. Thanks again for the help. :)
